<?php

namespace App\Support;

use Illuminate\Support\Facades\Log;

/**
 * The site's animation catalog, generated by python/tools/animations.py into
 * resources/content/animations.json (docs/ARCHITECTURE.md §7 and §11).
 *
 * Each entry keeps every field of the JSON file and gains a "title" resolved for
 * the requested locale (falling back to French, then to the keyframes name):
 *   ['n' => 1, 'name' => 'ap-…', 'group' => 'brand', 'demo' => 'shape', 'file' => 'css/…',
 *    'scene' => null, 'label' => ['fr' => …, 'en' => …], 'title' => …,
 *    'dur' => '2.4s', 'ease' => 'ease-in-out', 'dir' => 'normal', 'iter' => 'infinite']
 *
 * A missing or malformed file yields an empty catalog — never an exception.
 */
final class AnimationCatalog
{
    /** Group order when the file does not declare one (§7). */
    public const GROUPS = ['brand', 'text', 'reveal', 'ui', 'ambient', 'loader', 'transition', 'page', 'scene'];

    private const DEFAULTS = [
        'demo' => 'shape',
        'file' => '',
        'scene' => null,
        'dur' => '2.4s',
        'ease' => 'ease-in-out',
        'dir' => 'normal',
        'iter' => 'infinite',
    ];

    private readonly string $path;

    /** @var array{groups: list<string>, animations: list<array<string, mixed>>}|null */
    private ?array $data = null;

    /** @var array<string, list<array<string, mixed>>> */
    private array $localized = [];

    public function __construct(?string $path = null)
    {
        $this->path = $path ?? resource_path('content/animations.json');
    }

    public function path(): string
    {
        return $this->path;
    }

    /**
     * Every animation, ordered by number.
     *
     * @return list<array<string, mixed>>
     */
    public function all(?string $locale = null): array
    {
        $locale ??= app()->getLocale();

        return $this->localized[$locale] ??= array_map(
            fn (array $entry): array => array_merge($entry, ['title' => $this->title($entry, $locale)]),
            $this->data()['animations'],
        );
    }

    /**
     * Animations grouped by group, groups in catalog order (empty groups omitted).
     *
     * @return array<string, list<array<string, mixed>>>
     */
    public function grouped(?string $locale = null): array
    {
        $grouped = array_fill_keys($this->data()['groups'], []);

        foreach ($this->all($locale) as $entry) {
            $grouped[$entry['group']][] = $entry;
        }

        return array_filter($grouped, fn (array $entries): bool => $entries !== []);
    }

    public function total(): int
    {
        return count($this->data()['animations']);
    }

    /**
     * Animations that belong to a service scene.
     *
     * @return list<array<string, mixed>>
     */
    public function forScene(string $slug, ?string $locale = null): array
    {
        return array_values(array_filter(
            $this->all($locale),
            fn (array $entry): bool => $entry['scene'] === $slug,
        ));
    }

    /**
     * Group keys in display order.
     *
     * @return list<string>
     */
    public function groups(): array
    {
        return $this->data()['groups'];
    }

    /**
     * @return array{groups: list<string>, animations: list<array<string, mixed>>}
     */
    private function data(): array
    {
        if ($this->data !== null) {
            return $this->data;
        }

        $empty = ['groups' => self::GROUPS, 'animations' => []];

        if (! is_file($this->path)) {
            return $this->data = $empty;
        }

        $json = json_decode((string) @file_get_contents($this->path), true);

        if (! is_array($json) || ! is_array($json['animations'] ?? null)) {
            Log::warning('Animation catalog ignored: '.$this->path.' is not a valid catalog.');

            return $this->data = $empty;
        }

        $animations = [];

        foreach (array_values($json['animations']) as $index => $entry) {
            $normalized = is_array($entry) ? $this->normalize($entry, $index) : null;

            if ($normalized !== null) {
                $animations[] = $normalized;
            }
        }

        usort($animations, fn (array $a, array $b): int => $a['n'] <=> $b['n']);

        return $this->data = [
            'groups' => $this->groupOrder($json['groups'] ?? null, $animations),
            'animations' => $animations,
        ];
    }

    /**
     * @param  array<mixed>  $entry
     * @return array<string, mixed>|null
     */
    private function normalize(array $entry, int $index): ?array
    {
        $name = $entry['name'] ?? null;
        $group = $entry['group'] ?? null;

        if (! is_string($name) || $name === '' || ! is_string($group) || $group === '') {
            return null;
        }

        $label = array_filter(
            is_array($entry['label'] ?? null) ? $entry['label'] : [],
            fn (mixed $text): bool => is_string($text) && $text !== '',
        );

        $normalized = [
            'n' => is_numeric($entry['n'] ?? null) ? (int) $entry['n'] : $index + 1,
            'name' => $name,
            'group' => $group,
        ];

        foreach (self::DEFAULTS as $key => $default) {
            $value = $entry[$key] ?? null;
            $normalized[$key] = is_scalar($value) && $value !== '' ? (string) $value : $default;
        }

        $normalized['label'] = $label;

        // Keep any extra field the generator may add.
        return $normalized + array_diff_key($entry, $normalized);
    }

    /**
     * @param  list<array<string, mixed>>  $animations
     * @return list<string>
     */
    private function groupOrder(mixed $declared, array $animations): array
    {
        $order = is_array($declared)
            ? array_values(array_filter($declared, fn (mixed $group): bool => is_string($group) && $group !== ''))
            : self::GROUPS;

        foreach ($animations as $entry) {
            if (! in_array($entry['group'], $order, true)) {
                $order[] = $entry['group'];
            }
        }

        return array_values(array_unique($order));
    }

    /**
     * @param  array<string, mixed>  $entry
     */
    private function title(array $entry, string $locale): string
    {
        return $entry['label'][$locale] ?? $entry['label']['fr'] ?? $entry['name'];
    }
}
